apiVersion: apps/v1
kind: Deployment
metadata: 
  generation: 1
  labels:
    app: emptydirtest
  name: emptydirtest
  namespace: test 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: emptydirtest 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: emptydirtest
    spec: 
      volumes:
        - name: vol
          emptyDir: {}
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', "while true; do echo $(hostname): $(date '+%d.%m.%Y %T') >> /datalogs/logs  && sleep 5;  done"]
        name: busybox
        volumeMounts:
          - name: vol
            mountPath:  /datalogs
      - image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent 
        name: multitool 
        volumeMounts:
          - name: vol
            mountPath:  /datalogs
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
 